definitions:
  cloud_handler.ErrorResponse:
    properties:
      details:
        description: |-
          Дополнительные детали (при наличии)
          example: "field 'file' is required"
      error:
        description: |-
          Краткое описание ошибки
          example: "Invalid request"
        type: string
      status:
        description: |-
          Код HTTP-статуса
          example: 400
        type: integer
    type: object
  dto.BadRequestErr:
    properties:
      error:
        description: 'example: invalid request data'
        type: string
    type: object
  dto.ConflictErr:
    properties:
      error:
        description: 'example: replay detected'
        type: string
    type: object
  dto.FileResponse:
    properties:
      created_at:
        type: string
      mime_type:
        type: string
      name:
        type: string
      obj_id:
        type: string
      url:
        type: string
    type: object
  dto.HandshakeFinalizeReq:
    description: Клиент шлёт RSA-OAEP(encrypted payload), закодированный в Base64.
      Подробнее про поле encrypted... Рандомные 32 байта - это сессионная строка,
      назовем её ks, которая лежит в payload payload - это сумма байтов (ks || nonce3
      || nonce2) signature3 - это подписанный payload приватным ключем клиента В конце
      encrypted это зашифрованные байты (payload || signature3(в DER формате)) encrypted
      - зашифрован RSA-OAEP публичным ключем сервера, отдается в формате Base64
    properties:
      encrypted:
        description: Base64(RSA-OAEP(encrypted payload || signature3(DER)))
        type: string
      signature3:
        type: string
    type: object
  dto.HandshakeFinalizeResp:
    description: Сервер возвращает подпись h4 = SHA256(Ks || nonce3 || nonce2), подписанную
      приватным ECDSA‑ключом сервера и закодированную в Base64.
    properties:
      signature4:
        description: Base64(DER‑подпись ответа сервера)
        type: string
    type: object
  dto.HandshakeInitReq:
    description: Клиент отправляет свои публичные ключи и nonce1, всё это подписано
      приватным ECDSA‑ключом. Все бинарные данные (ключи, подписи, nonce) закодированы
      в Base64 (DER для ключей и подписи).  rsa_pub_client - Base64(DER‑закодированный
      RSA‑публичный ключ клиента) ecdsa_pub_client - Base64(DER‑закодированный ECDSA‑публичный
      ключ клиента) nonce1 - Base64(8‑байтовый случайный nonce) signature1 - Base64(DER‑закодированная
      подпись SHA256(clientRSA || clientECDSA || nonce1) приватным ECDSA‑ключом клиента)
    properties:
      ecdsa_pub_client:
        type: string
      nonce1:
        type: string
      rsa_pub_client:
        type: string
      signature1:
        type: string
    type: object
  dto.HandshakeInitResp:
    description: Сервер отвечает своими публичными ключами и nonce2, всё это подписано
      приватным ECDSA‑ключом сервера. Все бинарные данные (ключи, подписи, nonce)
      закодированы в Base64 (DER для ключей и подписи).  client_id - SHA256‑хэш от
      (clientRSA‖clientECDSA), представлен в hex rsa_pub_server - Base64(DER‑закодированный
      RSA‑публичный ключ сервера) ecdsa_pub_server - Base64(DER‑закодированный ECDSA‑публичный
      ключ сервера) nonce2 - Base64(8‑байтовый случайный nonce) signature2 - Base64(DER‑подпись
      SHA256(rsaServer || ecdsaServer || nonce2 || nonce1 || clientID) приватным ECDSA‑ключом
      сервера)
    properties:
      client_id:
        type: string
      ecdsa_pub_server:
        type: string
      nonce2:
        type: string
      rsa_pub_server:
        type: string
      signature2:
        type: string
    type: object
  dto.InternalServerErr:
    properties:
      error:
        type: string
    type: object
  dto.SessionMessageReq:
    properties:
      client_signature:
        type: string
      encrypted_message:
        description: Base64(IV || ciphertext || tag)
        type: string
    type: object
  dto.SessionMessageResp:
    properties:
      plaintext:
        type: string
    type: object
  dto.UnauthorizedErr:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Документация о внутренней реализации и логики работы находится в папке
    docs
  title: SecureComm API
  version: "1.0"
paths:
  /files/all:
    get:
      description: Возвращает пре‐подписанные ссылки на скачивание всех файлов заданной
        категории (photo, unknown, video, text).
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Категория файлов (photo, unknown, video, text)
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список ссылок на все файлы категории
          schema:
            items:
              $ref: '#/definitions/dto.FileResponse'
            type: array
        "400":
          description: Некорректная категория
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Доступ запрещён
          schema:
            $ref: '#/definitions/cloud_handler.ErrorResponse'
        "404":
          description: Файлы не найдены
          schema:
            $ref: '#/definitions/cloud_handler.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/cloud_handler.ErrorResponse'
      security:
      - bearerAuth: []
      summary: Получение всех файлов категории
      tags:
      - Files
  /files/one/encrypted:
    post:
      consumes:
      - '*/*'
      description: Токен авторизации + зашифрованный поток в body + метаданные в заголовках
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Оригинальное имя файла (например photo.jpg)
        in: header
        name: X-Orig-Filename
        required: true
        type: string
      - description: Оригинальный MIME-тип (например image/jpeg)
        in: header
        name: X-Orig-Mime
        required: true
        type: string
      - description: Категория файла (photo, video, text, unknown)
        in: header
        name: X-File-Category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Успешно: JSON с metadata + presigned URL'
          schema:
            $ref: '#/definitions/dto.FileResponse'
        "400":
          description: Некорректные заголовки или body
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Проблема с авторизацией
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - bearerAuth: []
      summary: Загрузка зашифрованного файла “на лету”
      tags:
      - Files
  /handshake/finalize:
    post:
      consumes:
      - application/json
      description: |-
        ЗАПРОС ОТ КЛИЕНТА:
        Клиент шлёт RSA-OAEP(encrypted payload), закодированный в Base64.
        и signature подписанный payload приватным ключем клиента
        об отправляемых полях клиентом encrypted и signature3:
        Рандомные 32 байта - это сессионная строка, назовем её ks, которая лежит в payload
        payload - это сумма байтов (ks || nonce3 || nonce2)
        signature3 - это подписанный payload приватным ключем ECDSA клиента в base64

        ОТВЕТ ОТ СЕРВЕРА:
        Сервер возвращает подпись signature4 = SHA256(Ks || nonce3 || nonce2), подписанную приватным ECDSA-ключом сервера и закодированную в Base64.
      parameters:
      - description: Параметры завершения Handshake
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.HandshakeFinalizeReq'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ сервера
          schema:
            $ref: '#/definitions/dto.HandshakeFinalizeResp'
        "400":
          description: Некорректный JSON или параметры
          schema:
            $ref: '#/definitions/dto.BadRequestErr'
        "401":
          description: Unauthorized или подпись не верна
          schema:
            $ref: '#/definitions/dto.UnauthorizedErr'
        "409":
          description: Conflict — повторный запрос (replay-detected)
          schema:
            $ref: '#/definitions/dto.ConflictErr'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.InternalServerErr'
      security:
      - bearerAuth: []
      summary: Завершает Handshake
      tags:
      - handshake
  /handshake/init:
    post:
      consumes:
      - application/json
      description: |-
        ЗАПРОС ОТ КЛИЕНТА:
        Клиент отправляет свои публичные ключи и nonce1, всё это подписано приватным ECDSA-ключом.
        Все бинарные данные (ключи, подписи, nonce) закодированы в Base64 (DER для ключей и подписи).

        rsa_pub_client - Base64(DER-закодированный RSA-публичный ключ клиента)
        ecdsa_pub_client - Base64(DER-закодированный ECDSA-публичный ключ клиента)
        nonce1 - Base64(8-байтовый случайный nonce)
        signature1 - Base64(DER-закодированная подпись SHA256(clientRSA || clientECDSA || nonce1) приватным ECDSA-ключом клиента)

        ОТВЕТ ОТ СЕРВЕРА:
        Сервер отвечает своими публичными ключами и nonce2, всё это подписано приватным ECDSA-ключом сервера.
        Все бинарные данные (ключи, подписи, nonce) закодированы в Base64 (DER для ключей и подписи).

        client_id будет извлечён из JWT (Bearer-токена).
        rsa_pub_server - Base64(DER-закодированный RSA-публичный ключ сервера)
        ecdsa_pub_server - Base64(DER-закодированный ECDSA-публичный ключ сервера)
        nonce2 - Base64(8-байтовый случайный nonce)
        signature2 - Base64(DER-подпись SHA256(rsaServer || ecdsaServer || nonce2 || nonce1 || clientID) приватным ECDSA-ключом сервера)
      parameters:
      - description: Параметры инициации Handshake
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.HandshakeInitReq'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ сервера
          schema:
            $ref: '#/definitions/dto.HandshakeInitResp'
        "400":
          description: Некорректный JSON или параметры
          schema:
            $ref: '#/definitions/dto.BadRequestErr'
        "401":
          description: Unauthorized или ошибка подписи
          schema:
            $ref: '#/definitions/dto.UnauthorizedErr'
        "409":
          description: Conflict — повторный запрос (replay-detected)
          schema:
            $ref: '#/definitions/dto.ConflictErr'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.InternalServerErr'
      security:
      - bearerAuth: []
      summary: Инициализация Handshake
      tags:
      - handshake
  /session/test:
    post:
      consumes:
      - application/json
      description: |-
        Клиент шлёт серверу зашифрованный пакет, объединяющий метаданные и payload данные:
        timestamp - время отправки клиента в формате Unix миллисекунд (8 байт)
        nonce - криптографически стойкое случайное значение (16 байт) для защиты от replay
        IV - инициализационный вектор AES-CBC (16 байт)
        ciphertext - результат AES-256-CBC шифрования сессионного payload'а + PKCS#7
        tag - HMAC-SHA256 от (IV||ciphertext) для целостности данных

        по итогу клиент отправляет:
        encrypted_message = timestamp(8 byte) || nonce(16 byte) || IV(16 byte) || ciphertext || tag(32 byte)
        client_signature = Base64(DER‑закодированная подпись SHA256(timestamp || nonce || IV || ciphertext || tag) приватным ECDSA‑ключом клиента

        Сервер выполняет следующие шаги:
        Декодирует Base64 и извлекает blob.
        Извлекает timestamp и nonce из первых 24 байт и проверяет не использован ли nonce и если diff = (client_timestamp - server_timestamp) > допустимому окну(30секунд). если это так, то запрос отклоняется с ошибкой
        Получает K_enc и K_mac по clientID, иначе 401 Unauthorized;
        Проверяет HMAC-SHA256(iv||ciphertext), иначе 401 Unauthorized;
        Расшифровывает AES-256-CBC, снимает PKCS#7 padding, иначе 400 Bad Request;
        Возвращает JSON с plaintext - декодированный userData.
      parameters:
      - description: Метаданные + зашифрованный payload в Base64
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.SessionMessageReq'
      produces:
      - application/json
      responses:
        "200":
          description: 'Успешный ответ: plaintext'
          schema:
            $ref: '#/definitions/dto.SessionMessageResp'
        "400":
          description: Неверный формат Base64, устаревший timestamp или padding
          schema:
            $ref: '#/definitions/dto.BadRequestErr'
        "401":
          description: Session not found или проверка HMAC не прошла
          schema:
            $ref: '#/definitions/dto.UnauthorizedErr'
        "409":
          description: Повторное использование nonce (replay)
          schema:
            $ref: '#/definitions/dto.ConflictErr'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.InternalServerErr'
      security:
      - bearerAuth: []
      summary: Тестовое расшифрование и проверка целостности сессионного сообщения
      tags:
      - session
securityDefinitions:
  BearerAuth:
    description: '"Bearer {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
